cv2.error: OpenCV(4.5.1) /tmp/pip-wheel-qd18ncao/opencv-python/opencv/modules/dnn/src/caffe/caffe_io.cpp:1133: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "ssd_mobilenet_coco/frozen_inference_graph.pb" in function 'ReadProtoFromBinaryFile'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/Desktop/whiteCane/main.py", line 32, in <module>
    model = cv2.dnn_DetectionModel(frozen_model, config_file)
SystemError: <class 'cv2.dnn_DetectionModel'> returned a result with an error set
